### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by tillig**
I noticed the project was pretty out of date with respect to...

- Dependencies (test framework, analyzers)
- Build script
- Analyzer settings
- editorconfig, gitignore, etc.
- .NET SDK

This PR updates all of that stuff and fixes all the analyzer issues that appear once the settings are updated to core Autofac settings. It's a lot of churn, but no actual executing code changed outside of things like "add missing braces" or "rename parameter on private method" sorts of changes.

### CODE REVIEW

**Comment by tillig** [comment]
Looks like I need to figure out why the Autofac core build isn't handling the global.json here. I see the .NET SDK is installed but it's not being added to the path.

**Comment by alistairjevans** [comment]
Reckon it's probably the same problem from here: https://github.com/autofac/Autofac.Extensions.DependencyInjection/commit/18704198b0b04420dda35ad92244b5f425686286

**Comment by tillig** [comment]
New issue that wasn't showing up with out `git clean`. Analyzer update. On it.

**Comment by tillig** [comment]
OK, build is running, good to go.

**Comment by alistairjevans** [comment]
Looks like the codecov changes are false positives due to changing one-line exception check+throw to proper formatting.

**Review by alistairjevans — APPROVED** [review]

**Pull request merged**
